# Site settings
name: Dan Moreno
title: Dan Moreno | Software Engineer
description: Designer and Software Engineer
url: http://danmoreno.xyz
baseurl: ""
email: dmorenocuellar@gmail.com
cover: http://danmoreno.xyz/img/
logo: https://brittanychiang.com/img/emojis/technologist.png
resume: http://danmoreno.xyz/resume.pdf
portfolio: http://danmoreno.xyz/portfolio.pdf
social:
  - title: email
    url: mailto:dmorenocuellar@gmail.com
  - title: snapchat
    url: https://www.snapchat.com/add/dmorenocuellar
  - title: instagram
    url: https://instagram.com/morendawg
  - title: github
    url: https://github.com/morendawg
  - title: linkedin
    url: https://www.linkedin.com/in/dmorenocuellar/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
